test

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -6,233 +6,233 @@ on:
     branches: [ dev ]
 
 jobs:
-  Lint:
-    runs-on: self-hosted
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # Lint:
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: lint App
-        run: find ./sample-app-master -type f -name "*.php" -exec php -l {} \;
+  #     - name: lint App
+  #       run: find ./sample-app-master -type f -name "*.php" -exec php -l {} \;
 
-  terraform-apply-iaac:
-    needs: Lint
-    runs-on: self-hosted
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # terraform-apply-iaac:
+  #   needs: Lint
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.7 
+  #     - name: Set up Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.5.7 
       
-      - name: Export Azure Service Principal creds for Terraform
-        run: |
-          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
-          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
-          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
-          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
+  #     - name: Export Azure Service Principal creds for Terraform
+  #       run: |
+  #         echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
+  #         echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
+  #         echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
+  #         echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
 
 
-      - name: Create VM
-        working-directory: infra_iaas
-        run: |
-          echo "developer_name=${{ github.actor }}"
-          terraform init -backend-config="path=terraform/dev/iaas/${{ github.actor }}"
-          terraform validate
-          terraform plan -var-file="dev.tfvars"
-          terraform apply -auto-approve -var-file="dev.tfvars"
-          terraform output -json public_ip > vm_ip.txt
-          cat vm_ip.txt
+  #     - name: Create VM
+  #       working-directory: infra_iaas
+  #       run: |
+  #         echo "developer_name=${{ github.actor }}"
+  #         terraform init -backend-config="path=terraform/dev/iaas/${{ github.actor }}"
+  #         terraform validate
+  #         terraform plan -var-file="dev.tfvars"
+  #         terraform apply -auto-approve -var-file="dev.tfvars"
+  #         terraform output -json public_ip > vm_ip.txt
+  #         cat vm_ip.txt
 
-      - name: Upload inventory.ini as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: inventory-file-dev
-          path: infra_iaas/inventory_dev.ini
+  #     - name: Upload inventory.ini as artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: inventory-file-dev
+  #         path: infra_iaas/inventory_dev.ini
 
-      - name: check inventory.ini
-        run: |
-          cat infra_iaas/inventory_dev.ini
+  #     - name: check inventory.ini
+  #       run: |
+  #         cat infra_iaas/inventory_dev.ini
           
 
-      - name: Upload VM IP
-        uses: actions/upload-artifact@v4
-        with:
-          name: vm-ip
-          path: infra_iaas/vm_ip.txt
+  #     - name: Upload VM IP
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: vm-ip
+  #         path: infra_iaas/vm_ip.txt
 
-#  terraform-apply-caac:
-#    needs: Lint
-#    runs-on: self-hosted
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v4
-#
-#      - name: Set up Terraform
-#        uses: hashicorp/setup-terraform@v2
-#        with:
-#          terraform_version: 1.5.7
-#
-#      - name: Export Azure Service Principal creds for Terraform
-#        run: |
-#          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
-#          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
-#          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
-#          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
-#
-#
-#      - name: Create VM
-#        working-directory: infra_caas
-#        run: |
-#          export TF_VAR_dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}
-#          export TF_VAR_dockerhub_password=${{ secrets.DOCKERHUB_TOKEN }}
-#          echo "developer_name=${{ github.actor }}"
-#          terraform init -backend-config="path=terraform/dev/caas/${{ github.actor }}"
-#          terraform validate
-#          terraform plan -var-file="dev.tfvars"
-#          terraform apply -auto-approve -var-file="dev.tfvars"
-#
+ terraform-apply-caac:
+   needs: Lint
+   runs-on: self-hosted
+   steps:
+     - name: Checkout code
+       uses: actions/checkout@v4
 
-  ansible:
-    needs: terraform-apply-iaac
-    runs-on: self-hosted
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+     - name: Set up Terraform
+       uses: hashicorp/setup-terraform@v2
+       with:
+         terraform_version: 1.5.7
+
+     - name: Export Azure Service Principal creds for Terraform
+       run: |
+         echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
+         echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
+         echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
+         echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
+
+
+     - name: Create VM
+       working-directory: infra_caas
+       run: |
+         export TF_VAR_dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}
+         export TF_VAR_dockerhub_password=${{ secrets.DOCKERHUB_TOKEN }}
+         echo "developer_name=${{ github.actor }}"
+         terraform init -backend-config="path=terraform/dev/caas/${{ github.actor }}"
+         terraform validate
+         terraform plan -var-file="dev.tfvars"
+         terraform apply -auto-approve -var-file="dev.tfvars"
+
+
+  # ansible:
+  #   needs: terraform-apply-iaac
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
         
-      - name: Download inventory artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: inventory-file-dev
-          path: ansible   # where to place the downloaded file
+  #     - name: Download inventory artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: inventory-file-dev
+  #         path: ansible   # where to place the downloaded file
 
-      - name: Download VM IP artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: vm-ip
-          path: ~/vm
+  #     - name: Download VM IP artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: vm-ip
+  #         path: ~/vm
 
-      - name: Read VM IP
-        id: vm
-        run: |
-          VM_IP=$(grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' ~/vm/vm_ip.txt | head -n 1)
-          if [ -z "$VM_IP" ]; then
-            echo "Error: Could not extract VM IP"
-            exit 1
-          fi
-          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
-          echo "Using VM IP: $VM_IP"
+  #     - name: Read VM IP
+  #       id: vm
+  #       run: |
+  #         VM_IP=$(grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' ~/vm/vm_ip.txt | head -n 1)
+  #         if [ -z "$VM_IP" ]; then
+  #           echo "Error: Could not extract VM IP"
+  #           exit 1
+  #         fi
+  #         echo "VM_IP=$VM_IP" >> $GITHUB_ENV
+  #         echo "Using VM IP: $VM_IP"
 
-      - name: Setup SSH
-        env:
-          CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
-        run: |
-          id
-          mkdir -p ~/.ssh
-          echo "$CI_SSH_KEY" > ~/.ssh/id_rsa_tcloud
-          chmod 600 ~/.ssh/id_rsa_tcloud
-          touch ~/.ssh/known_hosts
-          ssh-keyscan -H ${{ env.VM_IP }} >> ~/.ssh/known_hosts
+  #     - name: Setup SSH
+  #       env:
+  #         CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
+  #       run: |
+  #         id
+  #         mkdir -p ~/.ssh
+  #         echo "$CI_SSH_KEY" > ~/.ssh/id_rsa_tcloud
+  #         chmod 600 ~/.ssh/id_rsa_tcloud
+  #         touch ~/.ssh/known_hosts
+  #         ssh-keyscan -H ${{ env.VM_IP }} >> ~/.ssh/known_hosts
 
-      - name: Run Ansible playbook
-        working-directory: ansible
-        run: ansible-playbook playbook.yml -i inventory_dev.ini --skip-tags prod
+  #     - name: Run Ansible playbook
+  #       working-directory: ansible
+  #       run: ansible-playbook playbook.yml -i inventory_dev.ini --skip-tags prod
 
-  stress-test:
-    needs: ansible
-    runs-on: self-hosted
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # stress-test:
+  #   needs: ansible
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      - name: Download VM IP artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: vm-ip
-          path: ~/vm
+  #     - name: Download VM IP artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: vm-ip
+  #         path: ~/vm
 
-      - name: Read VM IP
-        id: vm
-        run: |
-          VM_IP=$(grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' ~/vm/vm_ip.txt | head -n 1)
-          if [ -z "$VM_IP" ]; then
-            echo "Error: Could not extract VM IP"
-            exit 1
-          fi
-          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
-          echo "Using VM IP: $VM_IP"
+  #     - name: Read VM IP
+  #       id: vm
+  #       run: |
+  #         VM_IP=$(grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' ~/vm/vm_ip.txt | head -n 1)
+  #         if [ -z "$VM_IP" ]; then
+  #           echo "Error: Could not extract VM IP"
+  #           exit 1
+  #         fi
+  #         echo "VM_IP=$VM_IP" >> $GITHUB_ENV
+  #         echo "Using VM IP: $VM_IP"
 
-      - name: Run k6 stress test
-        run: |
-          mkdir -p k6-results
-          chmod 777 k6-results
-          docker run --rm -i \
-            -v $PWD/k6-results:/k6-results \
-            -e TARGET=http://${{ env.VM_IP }}:8081 \
-            grafana/k6:latest run - < k6-stress-test/stress_test.js
+  #     - name: Run k6 stress test
+  #       run: |
+  #         mkdir -p k6-results
+  #         chmod 777 k6-results
+  #         docker run --rm -i \
+  #           -v $PWD/k6-results:/k6-results \
+  #           -e TARGET=http://${{ env.VM_IP }}:8081 \
+  #           grafana/k6:latest run - < k6-stress-test/stress_test.js
 
-      - name: Upload k6 HTML report
-        uses: actions/upload-artifact@v4
-        with:
-          name: k6-html-report-stress-test
-          path: k6-results/report.html
+  #     - name: Upload k6 HTML report
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: k6-html-report-stress-test
+  #         path: k6-results/report.html
 
-  terraform-destroy-iaac:
-    needs: stress-test
-    runs-on: self-hosted
-    if: always()
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # terraform-destroy-iaac:
+  #   needs: stress-test
+  #   runs-on: self-hosted
+  #   if: always()
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.7 
+  #     - name: Set up Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.5.7 
           
-      - name: Export Azure Service Principal creds for Terraform
-        run: |
-          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
-          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
-          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
-          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
+  #     - name: Export Azure Service Principal creds for Terraform
+  #       run: |
+  #         echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
+  #         echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
+  #         echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
+  #         echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
 
-      - name: Destroy VM
-        working-directory: infra_iaas
-        run: | 
-          ls
-          terraform init -backend-config="path=terraform/dev/iaas/${{ github.actor }}"
-          terraform destroy  -auto-approve -var-file="dev.tfvars" 
+  #     - name: Destroy VM
+  #       working-directory: infra_iaas
+  #       run: | 
+  #         ls
+  #         terraform init -backend-config="path=terraform/dev/iaas/${{ github.actor }}"
+  #         terraform destroy  -auto-approve -var-file="dev.tfvars" 
   
 
-#  terraform-destroy-caac:
-#    needs: terraform-apply-caac
-#    runs-on: self-hosted
-#    if: always()
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v4
-#
-#      - name: Set up Terraform
-#        uses: hashicorp/setup-terraform@v2
-#        with:
-#          terraform_version: 1.5.7
-#
-#      - name: Export Azure Service Principal creds for Terraform
-#        run: |
-#          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
-#          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
-#          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
-#          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
-#
-#      - name: Destroy VM
-#        working-directory: infra_caas
-#        run: |
-#          export TF_VAR_dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}
-#          export TF_VAR_dockerhub_password=${{ secrets.DOCKERHUB_TOKEN }}
-#          terraform init -backend-config="path=terraform/dev/caas/${{ github.actor }}"
-#          terraform destroy  -auto-approve -var-file="dev.tfvars"
-#
+ terraform-destroy-caac:
+   needs: terraform-apply-caac
+   runs-on: self-hosted
+   if: always()
+   steps:
+     - name: Checkout code
+       uses: actions/checkout@v4
+
+     - name: Set up Terraform
+       uses: hashicorp/setup-terraform@v2
+       with:
+         terraform_version: 1.5.7
+
+     - name: Export Azure Service Principal creds for Terraform
+       run: |
+         echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
+         echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
+         echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
+         echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
+
+     - name: Destroy VM
+       working-directory: infra_caas
+       run: |
+         export TF_VAR_dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}
+         export TF_VAR_dockerhub_password=${{ secrets.DOCKERHUB_TOKEN }}
+         terraform init -backend-config="path=terraform/dev/caas/${{ github.actor }}"
+         terraform destroy  -auto-approve -var-file="dev.tfvars"
+
 
